name: Build & Deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}

    steps:
      # Checkout the repo
      - uses: actions/checkout@v2

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and push Docker Image
      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Preset Image Name
        run: echo "IMAGE_URL=$(echo ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:$(echo ${{ github.sha }} | cut -c1-7) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_URL }}
          build-args: |
            NEXT_PUBLIC_POSTHOG_KEY=${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}
            NEXT_PUBLIC_POSTHOG_HOST=${{ vars.NEXT_PUBLIC_POSTHOG_HOST }}

      # Deploy to CapRover
      - name: Deploy Image to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ vars.CAPROVER_SERVER }}"
          app: "${{ vars.APP_NAME }}"
          token: "${{ secrets.APP_TOKEN }}"
          image: ${{ env.IMAGE_URL }}

  notify:
    name: notify
    needs: [ build ]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: send discord message
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        if: always()
        with:
          args: 'Action finished on {{EVENT_PAYLOAD.repository.full_name}}'
      - name: send telegram message
        uses: appleboy/telegram-action@master
        if: always()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ‚úÖ *A build/deploy job finished*
            ‚ñ∂Ô∏è *Status: ${{ job.status }}*
            #Ô∏è‚É£ Run # ${{github.run_number}}. Event type: *${{ github.event_name }}*
            ü§° Developer: *${{github.actor}}*
            üí¨ Commit message: ${{ github.event.commits[0].message }}
            üîó Href: https://github.com/${{github.repository}}
            
            ‚ú® See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
          format: markdown
          disable_web_page_preview: "True"
